version: '3'

services:
  hb-server:
    image: node:19-alpine3.16
    command: sh -c "npm install && npm run dev"
    volumes:
      - './src:/hbserver/src'
      - './hbdata:/hbdata'
    working_dir: '/hbserver/src'
    environment:
      XHB_PATH: /hbdata/moneys.xhb
      HBS_PORT: 80
    ports:
      - 8080:80
    container_name: hb-server

  hb-client:
    image: grafana/grafana:main-ubuntu
    ports:
      - 80:3000
    restart: unless-stopped
    volumes:
      - hb-client-data:/var/lib/grafana/:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: hb-client

volumes:
  hb-client-data: