version: '3'

services:
  hb-server:
    image: renatus-cartesius/hbserver
    build: .
    volumes:
      - './hbdata:/hbdata'
      - './config:/hbserver/config'
    ports:
      - 8080:3000
    container_name: hb-server

  hb-client:
    image: grafana/grafana:main-ubuntu
    ports:
      - 80:3000
    restart: unless-stopped
    volumes:
      - hb-client-data:/var/lib/grafana/:rw
      - hb-client-etc:/etc/grafana/:rw
    container_name: hb-client

volumes:
  hb-client-data:
  hb-client-etc:
